on: [push]

name: Build Docker images

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
  DOCKER_ORGANIZATION: philipssoftware
  GITHUB_ORGANIZATION: philips-software
  COSIGN_PRIVATE_KEY: '${{ secrets.COSIGN_PRIVATE_KEY }}'
  COSIGN_PASSWORD: '${{ secrets.COSIGN_PASSWORD }}'
  COSIGN_PUBLIC_KEY: '${{ secrets.COSIGN_PUBLIC_KEY  }}'

jobs:
  build_tern:
    name: tern
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Build Docker Images with Tern 2.9.1
            dockerfile: 2/vanilla/tern/docker/Dockerfile
            tags: 2 2.9 2.9.1
          - name: Build Docker Images with scancode
            dockerfile: 2/scancode/tern/docker/Dockerfile.scancode
            tags: 2-scancode 2.9-scancode 2.9.1-scancode
          - name: Build Docker Images with Tern latest
            dockerfile: latest/tern/docker/Dockerfile
            tags: latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: recursive
      - name: ${{ matrix.name }} 
        uses: philips-software/docker-ci-scripts@v4.3.0
        with:
          dockerfile: ${{ matrix.dockerfile }} 
          image-name: tern
          tags: ${{ matrix.tags }}
          slsa-provenance: true
          sign: true
          sbom: true

  manual_build:
    name: tern manual
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: recursive

      - name: Build Docker Images with Tern and scancode latest
        uses: philips-software/docker-ci-scripts@v4.3.0
        with:
          dockerfile: docker/Dockerfile.scancode
          image-name: tern
          tags: latest-scancode
          base-dir: latest/tern
          slsa-provenance: true
          sign: true
          sbom: true

      - name: setup python 
        uses: actions/setup-python@v2.3.2
        with:
            python-version: '3.9' 

      - name: Build local version
        run: |
          cd local/tern
          python setup.py sdist
          cp -r dist ../../

      - name: Build Docker Images with Tern local
        uses: philips-software/docker-ci-scripts@v4.3.0
        with:
          dockerfile: local/tern/docker/Dockerfile.local
          image-name: tern
          tags: local
          slsa-provenance: true
          sign: true
          sbom: true

