on: [push]

name: Build Docker images

jobs:
  build_tern:
    name: tern
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker Images with Tern 2.4.0
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: 2/vanilla/tern/docker/Dockerfile
        image-name: tern
        tags: 2 2.5 2.5.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

    - name: Build Docker Images with scancode
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: 2/scancode/tern/docker/Dockerfile.scancode
        image-name: tern
        tags: 2-scancode 2.5-scancode 2.5.0-scancode
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

    - name: Build Docker Images with Tern latest
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: latest/tern/docker/Dockerfile
        image-name: tern
        tags: latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

    - name: setup python 
      uses: actions/setup-python@v2
      with:
          python-version: '3.9' 

    - name: Build local version
      run: |
        cd local/tern
        python setup.py sdist
        cp -r dist ../../

    - name: Build Docker Images with Tern local
      uses: philips-software/docker-ci-scripts@v3.2.1
      with:
        dockerfile: local/tern/docker/Dockerfile.local
        image-name: tern
        tags: local
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
