on: [push]

name: Build Docker images

jobs:
  build_tern:
    name: tern
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        depth: 0

    - name: Build Docker Images with Tern 2.2.0
      uses: philips-software/docker-ci-scripts@v2.2.2
      with:
        dockerfile: 2/tern
        image-name: tern
        tags: 2 2.2 2.2.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

    - name: Checkout latest version of tern 
      run: cd 2/tern && git pull origin master
        
    - name: Build Docker Images with Tern latest
      uses: philips-software/docker-ci-scripts@v2.2.2
      with:
        dockerfile: 2/tern
        image-name: tern
        tags: latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
