on: [push]

name: Build Docker images

jobs:
  build_dind_tern:
    name: dind-tern
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Images with Tern
      uses: philips-software/docker-ci-scripts@v1
      with:
        dockerfile: 1/dind-tern
        tags: tern tern:1 tern:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
